# Generated by Django 5.2.4 on 2025-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_language_remove_country_languages_country_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(related_name='countries', to='MainApp.language'),
        ),
    ]
